name: Java CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run Tests
      run: mvn test --file pom.xml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
    - name: Deploy to server
      # Ajoutez ici les étapes nécessaires pour déployer votre application
      run: echo "Déploiement de l'application Java"
